version: '3'
services:
  mongo:
    image: mongo:4.4.6-bionic
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - my-network

  app:
    build: .
    container_name: fastify-mongo-docker-api
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge